import Nav from "@/components/Nav";
import "@/styles/globals.css";
import Providers from "./Providers";

export const metadata = {
  icons: {
    icon: "/assets/images/favicon.jpeg",
  },
  title: "Averroes.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="main">
            <div className="gradient" />
          </div>

          <main className="app">
            <Nav />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
